class AddAutoGeneratedAndLateAlertToCalendarEvents < ActiveRecord::Migration[6.0]
  def change
    add_column :calendar_events, :auto_generated, :boolean
    add_column :calendar_events, :late_alert, :boolean
  end
end
